# Generated by Django 5.2.3 on 2025-06-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '__first__'),
        ('users', '0002_remove_user_date_of_birth_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('timebasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.timebasemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('shared.timebasemodel',),
        ),
    ]
