# Generated by Django 5.2.3 on 2025-06-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usertype_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
